name:  Generate Release

permissions:
  contents: write

# Trigger on every master branch push and pull request
on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install Yarn & pkg
        run: npm install --global pkg yarn
      - name: Install dependencies
        run: yarn install
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ComuStrike_Server-linux
            ComuStrike_Server-macos
            ComuStrike_Server-win.exe